spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: first-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth-service/**
#          filters:
#            - RewritePath=/first-service(?<segment>/?.*), $\{segment}

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://${EUREKA_URL:localhost:8761}/eureka
  instance:
    hostname: ${HOSTNAME:api-gateway}
    ip-address: ${CLIENT_IP_ADDRESS:localhost}
    prefer-ip-address: ${PREFER_IP_ADDRESS:true}
