spring:
  application:
    name: payment-service

server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: http://${EUREKA_URL:localhost:8761}/eureka
  instance:
    ip-address: ${CLIENT_IP_ADDRESS:localhost}
    hostname: ${HOSTNAME:payment-service}
    prefer-ip-address: ${PREFER_IP_ADDRESS:true}

oauth2:
  oauth:
    clientId: ${AUTH_CLIENTID:adminapp1}
    secret: ${AUTH_SECRET:password}
    publicKeyEndpointUri:  ${AUTH_URL:http://auth-service:8083/oauth/token_key}