server:
  port: 8079

spring:
  application:
    name: documentation-service

swagger:
  config:
    refresh-rate: 15000

eureka:
  client:
    service-url:
      default-zone: http://${EUREKA_URL:localhost:8761}/eureka
  instance:
    ip-address: ${CLIENT_IP_ADDRESS:localhost}
    hostname: ${HOSTNAME:documentation-service}
    prefer-ip-address: ${PREFER_IP_ADDRESS:true}