spring:
  application:
    name: eureka-service
  cloud:
    config:
      uri: http//localhost:8761
    loadbalancer:
      ribbon:
        enabled: true

server:
  port: 8761
eureka:
  instance:
    app-name: eureka-service
    hostname: eureka-service
    prefer-ip-address: ${PREFER_IP_ADDRESS:true}
    ip-address: ${CLIENT_IP_ADDRESS:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${EUREKA_URL:localhost}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"